
variables:
  GIT_STRATEGY: clone
before_script:
  - docker info
stages:
  - build
  - test
build_image_stage:
  stage: build
  tags:
    - shell_run_docker
  script:
    - docker login -u lamtv10 -p S4YugcbJfZetD551pwJa registry.ocs.com
    - docker push base_sfd_lamtv10
    - docker build  -t test_image_lamtv10:$CI_COMMIT_SHA .
    - docker tag test_image_lamtv10:$CI_COMMIT_SHA registry.ocs.com/lamtv10/software_deployment/test_image_lamtv10:$CI_COMMIT_SHA
    - docker push registry.ocs.com/lamtv10/software_deployment/test_image_lamtv10:$CI_COMMIT_SHA

run_image_stage:
  stage: test
  tags:
    - shell_run_test
  script:
    - docker ps -q --filter "name=lamtv10_software" | grep -q . && docker stop lamtv10_software && docker rm -fv lamtv10_software
    - docker pull registry.ocs.com/lamtv10/software_deployment/test_image_lamtv10:$CI_COMMIT_SHA
    - docker run -d --network=host --name lamtv10_software registry.ocs.com/lamtv10/software_deployment/test_image_lamtv10:$CI_COMMIT_SHA
