---
group_name: compute_password

# Cấu hình port cho các service trong Openstack
services_port: 
  keystone: 5000
  glance_api: 9292
  glance_registry: 9191
  nova_api: 8774
  nova_placement_api: 8778
  nova_metadata: 8775
  nova_novncproxy: 6080
  neutron_server: 9696
  horizon: 80
  cinder_api: 8776
  masakari_api: 15868

transport_url: rabbit://{% for node in groups['CONTROLLER'] %}openstack:{{RB_OPENSTACK}}@{{node}}:5672{% if not loop.last %},{% endif  %}{% endfor %}
memcached_servers: "{% for node in groups['CONTROLLER'] %}{{node}}:11211{% if not loop.last %},{% endif  %}{% endfor %}"

# Cấu hình đặc biệt cho nova-compute
use_vcpu_pin_set: true
cpu_pin: true
vcpu_pin_set: 3-17,39-53,21-35,57-71
rbd_store_ceph_conf: /etc/ceph/ceph.conf
nova_backend_ceph: false
resume_guests_state_on_host_boot : true
osapi_compute_unique_server_name_scope: false
nova_compute_logging_debug: false

vcpu_pin_set:
  epc_compute01: 3-7,19-23,10-15,26-31
  epc_compute02: 3-7,19-23,10-15,26-31
  epc_compute03: 3-9,23-29,13-19,33-39
  epc_compute04: 3-9,23-29,13-19,33-39
  epc_compute05: 3-17,39-53,21-35,57-71
  epc_compute06: 3-17,39-53,21-35,57-71
  epc_compute07: 3-17,39-53,21-35,57-71
  epc_compute08: 3-17,39-53,21-35,57-71
  epc_compute09: 3-17,39-53,21-35,57-71
  epc_compute10: 3-17,39-53,21-35,57-71
  epc_compute11: 3-17,39-53,21-35,57-71
  epc_compute12: 3-17,39-53,21-35,57-71
  epc_compute13: 3-17,39-53,21-35,57-71
  epc_compute14: 3-17,39-53,21-35,57-71



sriov_config:
  pci_passthrough_whitelist:
    epc_compute01: '[]'
    epc_compute02: '[]'
    epc_compute03: '[{ "devname": "ens2f0", "physical_network": "physnet2"}]'
    epc_compute04: '[]'
    epc_compute05: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute06: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute07: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute08: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute09: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute10: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute11: '[{ "devname": "ens2f0", "physical_network": "physnet2"} , { "devname": "ens1f0", "physical_network": "physnet1"}]'
    epc_compute12: '[{ "devname": "ens2f0", "physical_network": "physnet2"} ]'
    epc_compute13: '[{ "devname": "ens2f0", "physical_network": "physnet2"} ]'
    epc_compute14: '[]'
  physical_device_mappings:
    epc_compute01: ''
    epc_compute02: ''
    epc_compute03: physnet2:ens2f0
    epc_compute04: ''
    epc_compute05: physnet2:ens2f0, physnet1:ens1f0
    epc_compute06: physnet2:ens2f0, physnet1:ens1f0
    epc_compute07: physnet2:ens2f0, physnet1:ens1f0
    epc_compute08: physnet2:ens2f0, physnet1:ens1f0
    epc_compute09: physnet2:ens2f0, physnet1:ens1f0
    epc_compute10: physnet2:ens2f0, physnet1:ens1f0
    epc_compute11: physnet2:ens2f0, physnet1:ens1f0
    epc_compute12: physnet2:ens2f0
    epc_compute13: physnet2:ens2f0
    epc_compute14: ''