---

- name: 1.cp selinux.conf.j2 /etc/selinux/config
  block:
    - include: extends/before.yml task_index=1
    - template:
        src: selinux.conf.j2
        dest: /etc/selinux/config
        owner: root
        group: root
        mode: '0644'
        backup: yes
      register: infos
    - include:  extends/after_ok.yml task_index=1 info={{ infos  }}
  rescue:
    - include:  extends/after_failse.yml task_index=1 info={{ infos  }}
    - fail: msg={{ infos }}
  tags: [ 'install', '1' ]

- name: 2.stop selinux
  block:
    - include: extends/before.yml task_index=2
    - command: '{{ item }}'
      with_items:
        - sudo setenforce 0
      register: infos
    - include:  extends/after_ok.yml task_index=2 info={{ infos  }}
  rescue:
    - include:  extends/after_failse.yml task_index=2 info={{ infos  }}
    - fail: msg={{ infos }}  
  tags: [ 'install', '2' ]


#- name: 3.systemctl stop iptables
#  block:
#    - include: extends/before.yml task_index=3
#    - systemd:
#        name: iptables
#        enabled: no
#        masked: no
#      register: infos
#      #ignore_errors: yes
#    - include:  extends/after_ok.yml task_index=3 info={{ infos  }}
#  rescue:
#    - include:  extends/after_failse.yml task_index=3 info={{ infos  }}
#  tags: [ 'install', '3' ]
#
#
#
#- name: 4.systemctl stop firewalld
#  block:
#    - include: extends/before.yml task_index=4
#    - systemd:
#        name: firewalld
#        enabled: no
#        masked: no
#      register: infos
#    - include:  extends/after_ok.yml task_index=4 info={{ infos  }}
#  rescue:
#    - include:  extends/after_failse.yml task_index=4 info={{ infos  }}
#  tags: [ 'install', '4' ]
#
#
#
#- name: 5.test_ansible_command
#  block:
#    - include: extends/before.yml task_index=5
#    - command: '{{ item }}'
#      with_items:
#        - echo "{{ inventory_hostname }}     "
#        - touch /home/"{{ service_name }}"
#    #    - cp /home/lamtv10/lkt /home/lamtv10/
#        - echo 'group_name'
#    #    - echo "{{ansible_nodename}} - {{ansible_distribution}}"
#      register: infos
#    - include:  extends/after_ok.yml task_index=5 info={{ infos  }}
#  rescue:
#    - include:  extends/after_failse.yml task_index=5 info={{ infos  }}
#  tags: [ 'install', '5' ]
#
#
#- name: 6.cp local.repo.j2 /etc/yum.repos.d/local.repo
#  block:
#    - include: extends/before.yml task_index=6
#    - template:
#        src: local.repo.j2
#        dest: /etc/yum.repos.d/local.repo
#        owner: root
#        group: root
#        mode: '0644'
#        backup: yes
#      register: infos
#    - include:  extends/after_ok.yml task_index=6 info={{ infos  }}
#  rescue:
#    - include:  extends/after_failse.yml task_index=6 info={{ infos  }}
#  tags: [ 'install', '6' ]
#
#
#
#- name: 7.cp docker.repo.j2 /etc/yum.repos.d/docker.repo
#  block:
#    - include: extends/before.yml task_index=7
#    - template:
#        src: docker.repo.j2
#        dest: /etc/yum.repos.d/docker.repo
#        owner: root
#        group: root
#        mode: '0644'
#        backup: yes
#      register: infos
#    - include:  extends/after_ok.yml task_index=7 info={{ infos  }}
#  rescue:
#    - include:  extends/after_failse.yml task_index=7 info={{ infos  }}
#  tags: [ 'install', '7' ]
