base_distro: rhel7.7
openstack_release: queens
network_interface: eno1
NTP_NETWORK: 172.16.29.0/25
subnet1: 172.16.29.0/24
subnet2: 172.16.31.0/24
CONTROLLER_HOST: os-controller
keystone_auth_url: http://os-controller:5000/v3
project_domain_name: Default
user_domain_name: Default
project_name: service
ADMIN_PASS: Vttek@123
REGION_NAME: North_VN
CELL_NAME: cell1
HUB: controller01
first_controller: '{{ HUB }}'
chrony_server: '{{ HUB }}'
INTERNAL_VIP_ADDRESS: 172.16.29.199
VIP_PUBLIC: '{{ INTERNAL_VIP_ADDRESS }}'
HAPROXY_STATS_PORT: 1995
HAPROXY_STATS_USER: cloud
HAPROXY_STATS_PASS: GdYc6d8jYwURfAn5A3sc08Ipt5zcanPl
VIP_PRIVATE_INF: '{{ network_interface }}'
VIP_PRIVATE: '{{ INTERNAL_VIP_ADDRESS }}'
ROUTER_ID: 100
OS_CONTROLLER: '{{ INTERNAL_VIP_ADDRESS }}'
sriov_dev_name: ens2f0
KEEPALIVED_PRIORS:
  controller01: 3
  controller02: 2
  controller03: 1
pc_weight:
  controller01: 43
  controller02: 30
  controller03: 20
